name: lifton
description: Fitness App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  http: ^0.13.6
  intl: ^0.18.1
  table_calendar: ^3.0.9
  url_launcher: ^6.1.9
  file_picker: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
